INSERT INTO languages (language, translation) VALUES ( 'EN', 'Hello World!');
INSERT INTO languages (language, translation) VALUES ( 'CN', '你好世界!');
INSERT INTO languages (language, translation) VALUES ( 'CZ', 'Ahoj světe!');
INSERT INTO languages (language, translation) VALUES ( 'FR', 'Bonjour monde!');
INSERT INTO languages (language, translation) VALUES ( 'DE', 'Hallo Welt!');
INSERT INTO languages (language, translation) VALUES ( 'GR', 'Γειά σου Κόσμε!');
INSERT INTO languages (language, translation) VALUES ( 'IT', 'Ciao mondo!');
INSERT INTO languages (language, translation) VALUES ( 'RS', 'Здраво Свете!');
INSERT INTO languages (language, translation) VALUES ( 'ES', '¡Hola Mundo!');
INSERT INTO languages (language, translation) VALUES ( 'NO', 'Hei Verden!');